# Generated by Django 3.2.23 on 2024-02-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_id',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
